config/routes.rb
Uurrooster::Application.routes.draw do

  get "sync" => "Courses#sync"
  match "robots.txt" => "Students#robots"
  match "view/lecture/:id" => "Lectures#show", :as => :lecture
  match "view/remove_custom_lecture/:nr(/:id)" => "Lectures#remove", :as => :remove_custom_lecture
  match "view/add_custom_lecture/:nr" => "Lectures#add", :as => :add_custom_lecture
  match "view/profs/:id" => "Profs#show", :as => :prof
  match "view/course/:id" => "Courses#show", :as => :course
  match "view/courses" => "Courses#list", :as => :courses_list
  match "view/students" => "Students#list", :as => :index
  match "view/(:id)/edit" => "Students#edit", :as => :edit
  match "view/(:id)/save" => "Students#save", :as => :save
	match "view/:id/edit_custom_course(/:courseid)" => "Courses#edit", :as => :edit_custom_course
	match "view/:id/save_custom_course(/:courseid)" => "Courses#save", :as => :save_custom_course
	match "view/:id/remove_custom_course/:course" => "Students#remove_custom_course", :as => :remove_custom_course
	match "view/:id/add/:course" => "Students#add_course", :as => :add_course
	match "view/:id/remove/:course" => "Students#remove_course", :as => :remove_course
  match "view/:id/now" => "Students#now"
  match "view/:id/today" => "Students#day"
  match "view/:id/day/:day" => "Students#day"
  match "view/:id/:week/:day" => "Students#day"
  match "view/:id/:week" => "Students#show", :as => :show_week
	match "view/:id" => "Students#show", :as => :show
	match ":id" => "Students#show"
  match "ical/:id" => "Students#ical", :as => :ical

  root :to => "Students#list"

  # See how all your routes lay out with "rake routes"
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_and_belongs_to_many :courses, :class_name => "Course"
  has_many :custom_courses

  validates_uniqueness_of :name

  def all_courses
    courses + custom_courses
  end

  def lectures week=nil, day=nil
    l = all_courses.map{|c| c.lectures}.flatten #.select{|l| not l.deleted }
    #     puts "week: #{week}"
    #     puts l.map{|le| "#{le.weeks} -=- #{le.course.name}"}.join("\n")
    if week 
      if day
        l.select{|lecture| (lecture.week_nrs.member? week.to_i) && (lecture.day == day)}.sort{|a,b| a.starts <=> b.starts}
      else
        l.select{|lecture| lecture.week_nrs.member? week.to_i}
      end
    else
      l
    end
  end

	def all_lectures
		l = all_courses.map{|c| c.lectures}.flatten #.select{|l| not l.deleted }
    all = {}
    (1..52).map do |week|
      all[week] = l.select{|lecture| lecture.week_nrs.member? week.to_i}
    end
    all
	end

  def self.find_by_id_or_name id
    if id.to_i == 0
      Student.find(:first, :conditions => ["name = ?", id])
    else
      Student.find id
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  require "icalendar"
  require "date"
  require "tzinfo"

  def list
    @students = Student.all.sort{|a,b| a.name.downcase <=> b.name.downcase }
    respond_to do |format|
      format.html
    end
  end

  def show
    @student = Student.find_by_id_or_name params[:id] if params[:id]

    @currentweek = Lecture.currentweek

    @week = params[:week] || @currentweek
    @week = nil if @week.to_i == 0

    respond_to do |format|
      if @student
        format.html
      else
        format.html { redirect_to index_url }
      end
    end
  end

  def day
    @student = Student.find_by_id_or_name params[:id] if params[:id]
    @today = true
    @week = Lecture.currentweek
    @day = ((Time.now.strftime("%w").to_i - 1) % 7).to_i
    dotw = ["ma","di","wo","do","vr","za","zo"]

    if params[:week] && params[:week].to_i != 0
      @week = params[:week]
      @today = false
    end

    if params[:day] && dotw.include?(params[:day])
      @day = dotw.index params[:day]
      @today = false
    end

    respond_to do |format|
      if @student
        lectures = @student.lectures(@week, @day)
        format.html { render :layout => false, :text => (@today ? "" : "#{dotw[@day]} week #{@week}: ") + (lectures.empty? ? "geen les!" : lectures.join(" || ")) }
      else
        format.html { render :layout => false, :text => "Student not found - go to http://uurrooster.phoenix.rave.org/edit to create a new account, then try again" }
      end
    end
  end

  def now
    @student = Student.find_by_id_or_name params[:id] if params[:id]
    @week = Lecture.currentweek
    @day = ((Time.now.strftime("%w").to_i - 1) % 7).to_i
    @now = Time.now.strftime("%H%M").to_i

    respond_to do |format|
      if @student
        lectures = @student.lectures(@week, @day).select{|lecture| lecture.starts == @now || lecture.ends == @now || (lecture.starts..lecture.ends).member?(@now) }
        format.html { render :layout => false, :text => (lectures.empty? ? "geen les!" : lectures.join(" || ")) }
      else
        format.html { render :layout => false, :text => "Student not found - go to http://uurrooster.phoenix.rave.org/edit to create a new account, then try again" }
      end
    end
  end

  def ical
    @student = Student.find_by_id_or_name params[:id] if params[:id]
    if @student
      @cal = Icalendar::Calendar.new

      tz = TZInfo::Timezone.get('Europe/Brussels')

      all_lects = @student.all_lectures

      (1..52).each do |week|
        all_lects[week].each do |lecture|
          @cal.event do
            dtstart tz.local_to_utc(lecture.starts_t(week) + 364*24*60*60).strftime("%Y%m%dT%H%M%S")
            dtend tz.local_to_utc(lecture.ends_t(week) + 364*24*60*60).strftime("%Y%m%dT%H%M%S")
            summary lecture.name
            location lecture.room
            klass "PUBLIC"
          end
        end if all_lects[week]
      end

      @cal.publish

      headers['Content-Type'] = "text/calendar; charset=UTF-8"
      render :layout => false, :text => @cal.to_ical
    else
      redirect_to index_url
    end
  end

  def edit
    @student = (params[:id] && Student.find_by_id_or_name(params[:id])) || Student.new
    @courses = Course.all.sort{|a,b| a.name.downcase <=> b.name.downcase }
    respond_to do |format|
      format.html
    end
  end

  def save
    @student = (params[:oldname] && Student.find_by_id_or_name(params[:oldname])) || (params[:student][:name] && Student.find_by_id_or_name(params[:student][:name])) || Student.new
    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to(show_url(params[:student][:name].downcase)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def add_course
    @student = Student.find_by_id_or_name params[:id]
    @student.courses << Course.find(params[:course])
    @courses = Course.all.sort{|a,b| a.name.downcase <=> b.name.downcase }
    respond_to do |format|
      format.html { redirect_to edit_url(params[:id]) }
      format.js
    end
  end

  def remove_course
    @student = Student.find_by_id_or_name params[:id]
    @student.courses.delete Course.find(params[:course])
    @courses = Course.all.sort{|a,b| a.name.downcase <=> b.name.downcase }
    respond_to do |format|
      format.html { redirect_to edit_url(params[:id]) }
      format.js
    end
  end

  def remove_custom_course
    @student = Student.find_by_id_or_name params[:id]
    @courses = Course.all.sort{|a,b| a.name.downcase <=> b.name.downcase }
    course = CustomCourse.find params[:course]
    course.lectures.each do |lecture|
      lecture.destroy
    end
    course.destroy
    respond_to do |format|
      format.html { redirect_to edit_url(params[:id]) }
      format.js
    end
  end

end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/students/_courses.html.erb
<table>
	<% @student.all_courses.each do |c| %>
		<tr>
      <td><%= link_to "Remove", c.remove_path(@student.name), :remote => true %></td>
			<td><%= link_to c.name, c.path %></td>
		</tr>
	<% end %>
  <tr>
    <td colspan=2><%= link_to "Add custom course", edit_custom_course_path(@student.name) %></td>
  </tr>
</table>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= form_for @student, :url => save_path do |f| %>
  <%= hidden_field_tag 'oldname', @student.name %>
  <p>
    Name: <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Back', index_path %>

<% if @student.id %>
<%= link_to 'Show', show_path(@student.name) %>
<p>
  <div id="student_courses">
    <%= render :partial => 'courses' %>
  </div>

  <hr />

  <table>
    <% @courses.each do |c| %>
      <tr>
        <td><%= link_to "Add", add_course_path(@student.name, c.id), :remote => true %></td>
        <td><%= link_to c.name, c.path %></td>
      </tr>
    <% end %>
  </table>
</p>
<% end %>

app/views/students/list.html.erb
<h1>All Students</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>

<% for student in @students %>
  <tr>
    <td><%= link_to student.name, show_path(student.name) %></td>
  </tr>
<% end %>
</table>

<%= link_to "New student", edit_path %>

app/views/students/show.html.erb
<p>
  <b>Name:</b>
  <%=h @student.name %>
</p>

<%#<p>%>
<%#  date used: <%= @currenttime.strftime "%A %d %B %Y" +|%>
<%#</p>%>
<p>
  currently showing <%= @week ? "week " + @week.to_s : "all weeks" %>
  <form method=POST action="<%= show_path(@student.name) %>">
    show week: (0 for all)
    <input id="week" name="week" value="<%= @currentweek %>" />
    <input type=submit value="show" />
  </form>
  <form method=POST action="<%= show_week_path(@student.name, (@week.to_i - 1) % 52) %>">
    <input type=submit value="prev" />
  </form>
  <form method=POST action="<%= show_week_path(@student.name, (@week.to_i + 1) % 52) %>">
    <input type=submit value="next" />
  </form>
</p>

<% lectures = @student.lectures(@week) %>
<% @time_start = lectures.empty? ? 800 : lectures.map{|l| l.starts}.min - 100 %>
<% @time_end = lectures.empty? ? 1800 : lectures.map{|l| l.ends}.max + 100 %>
<table border = 1>
	<tr>
		<td style="background:#dd0;">
			day \ time
		</td>
		<% time = @time_start %>
		<% shifts = [30, 70] %>
		<% while time < @time_end do %>
			<td style="background:#dd0;text-align:center;">
				<%= sprintf "%d:%02d", time / 100, time % 100 %>
			</td>
			<% time += shifts.first %>
			<% shifts << shifts.shift %>
		<% end %>
	</tr>

	<% days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"] %>
	<% days.each_with_index do |day, day_i| %>
		<% lectures_of_the_day = [lectures.select{|l| l.day == day_i}] %>

		<% if !lectures_of_the_day.last.empty? %>
			<%# this piece divides the day in different tracks when there's things overlapping %>
			<% overlap = lectures_of_the_day.last.map{|a| lectures_of_the_day.last.map{|b| [a, b]}} %>
			<% overlap = overlap.inject{|a,b| a + b} %>
			<% overlap = overlap.select{|a,b| a.overlaps? b} %>
			<% while !overlap.empty? do %>
				<% result = [] %>
				<% overlap.each do |c| %>
					<% begin %>
						<% result << c.last %>
						<% lectures_of_the_day.last.reject!{|lecture| lecture == c.last} %>
					<% end unless result.member? c.first %>
				<% end %>
				<% lectures_of_the_day << result.uniq %>
				<% overlap = lectures_of_the_day.last.map{|a| lectures_of_the_day.last.map{|b| [a, b]}}.inject{|a,b| a + b}.select{|a,b| a.overlaps? b} %>
			<% end %>
		<% end %>
		<% lectures_of_the_day.reject!{|t| t.empty?} %>

		<% shifts = [30, 70] %>
		<% if lectures_of_the_day.empty? %>
			<tr>
				<td style="background:#dd0;">
					<%=h day %>
				</td>
				<td colspan=<%= ((@time_end - @time_start)/50.0).ceil %> style="background:#f2f2f2;text-align: center;"><b>FREE!</b></td>
			</tr>
		<% else %>
			<% lectures_of_the_day.each_with_index do |track, i| %>
				<tr>
					<% track.sort!{|a, b| a.starts <=> b.starts} %>
					<% time = @time_start %>
					<% if i == 0 %>
						<td rowspan=<%= lectures_of_the_day.length %>
							style="background:#dd0;">
							<%=h day %>
						</td>
					<% end %>
					<% track.each do |cur| %>
						<% while time < cur.starts do %>
              <td>&nbsp;</td>
							<% time += shifts.first %>
							<% shifts << shifts.shift %>
						<% end %>
            <% halfhours = ((cur.ends - cur.starts) / 50.0).ceil %>
						<td colspan=<%= halfhours %>
							style="background:#ccc;">
							<table>
								<tr>
									<td colspan=2 id="course_name">
										<%= link_to cur.name, cur.path %>
									</td>
								</tr>
								<tr>
									<td colspan=2 id="course_prof">
										<%= link_to cur.prof.name, prof_path(cur.prof.id) if cur.prof %>
									</td>
								</tr>
								<tr>
									<td id="course_location">
										<%=h cur.room %>
									</td>
									<td id="course_weeks" style="text-align:right;">
										<%=h cur.weeks %>
									</td>
								</tr>
							</table>
						</td>
						<% time = cur.ends %>
            <% halfhours.times do %>
              <% shifts << shifts.shift %>
            <% end %>
					<% end %>
					<% shifts << shifts.shift if shifts.first == 30 and time % 100 == 30 %>
					<% while time < @time_end do %>
						<td>&nbsp;</td>
						<% time += shifts.first %>
						<% shifts << shifts.shift %>
					<% end %>
				</tr>
			<% end %>
		<% end %>
	<% end %>

</table>

<%#<%= link_to 'Export to iCal', ical_path(@student) +| |%>
<%= link_to 'Edit', edit_path(@student.name) %> |
<%= link_to 'Back', index_path %>