config/routes.rb
Uurrooster::Application.routes.draw do

  get "sync" => "Courses#sync"
  match "robots.txt" => "Students#robots"
  match "view/lecture/:id" => "Lectures#show", :as => :lecture
  match "view/remove_custom_lecture/:nr(/:id)" => "Lectures#remove", :as => :remove_custom_lecture
  match "view/add_custom_lecture/:nr" => "Lectures#add", :as => :add_custom_lecture
  match "view/profs/:id" => "Profs#show", :as => :prof
  match "view/course/:id" => "Courses#show", :as => :course
  match "view/courses" => "Courses#list", :as => :courses_list
  match "view/students" => "Students#list", :as => :index
  match "view/(:id)/edit" => "Students#edit", :as => :edit
  match "view/(:id)/save" => "Students#save", :as => :save
	match "view/:id/edit_custom_course(/:courseid)" => "Courses#edit", :as => :edit_custom_course
	match "view/:id/save_custom_course(/:courseid)" => "Courses#save", :as => :save_custom_course
	match "view/:id/remove_custom_course/:course" => "Students#remove_custom_course", :as => :remove_custom_course
	match "view/:id/add/:course" => "Students#add_course", :as => :add_course
	match "view/:id/remove/:course" => "Students#remove_course", :as => :remove_course
  match "view/:id/now" => "Students#now"
  match "view/:id/today" => "Students#day"
  match "view/:id/day/:day" => "Students#day"
  match "view/:id/:week/:day" => "Students#day"
  match "view/:id/:week" => "Students#show", :as => :show_week
	match "view/:id" => "Students#show", :as => :show
	match ":id" => "Students#show"
  match "ical/:id" => "Students#ical", :as => :ical

  root :to => "Students#list"

  # See how all your routes lay out with "rake routes"
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  require 'curb'
  require 'i18n'
  require 'hpricot'

  private
  def fetch url
    Curl::Easy.download url, "/tmp/ruby.html"
    tmp = File.read "/tmp/ruby.html"
  rescue Exception => e
    raise e
  end

  public
  def show
    @course = Course.find(params[:id])
  end

  def list
    @courses = Course.all
  end

  def edit
    @student = Student.find_by_id_or_name(params[:id])
    @course = CustomCourse.find(params[:courseid]) if params[:courseid]
    @course = CustomCourse.new unless @course
    respond_to do |format|
      format.html
    end
  end

  def save
    @student = Student.find_by_id_or_name(params[:id])
    @course = CustomCourse.find(params[:courseid]) if params[:courseid]
    @course = CustomCourse.new unless @course
    @lectures = []
    params[:lectures].each do |nr,lecture|
      if lecture[:id]
        lect = CustomLecture.find lecture[:id]
        if lect
          lect.update_attributes(lecture)
          @lectures << lect
        else
          @lectures << CustomLecture.new(lecture)
        end
      else
        @lectures << CustomLecture.new(lecture)
      end
    end
    respond_to do |format|
      if @course.update_attributes(params[:course])
        @lectures.each do |lecture|
          lecture.custom_course_id = @course.id
          lecture.save
        end
        format.html { redirect_to(show_url(@student.name)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def sync
    Lecture.delete_all
#     Prof.delete_all
#     Course.delete_all

#     locus_url = "http://locus.vub.ac.be:8080/reporting/spreadsheet?idtype=name&template=Mod%2BSS&objectclass=module%2Bgroup&identifier="
#     locus_url = "http://locus.vub.ac.be/reporting/spreadsheet?idtype=name&template=Mod%2BSS&objectclass=module%2Bgroup&identifier="
    locus_url = "http://splus.cumulus.vub.ac.be:1184/reporting/spreadsheet?idtype=name&template=Mod%2BSS&objectclass=module%2Bgroup&identifier="
    days = {"ma"=>0,"di"=>1,"wo"=>2,"do"=>3,"vr"=>4,"za"=>5,"zo"=>6}
    @courses = {}
    errormsg = ""

#     doc = Hpricot fetch("http://locus.vub.ac.be/20102011/opleidingsonderdelen_1011.htm")
#     doc = Hpricot fetch("http://locus.vub.ac.be/20112012/opleidingsonderdelen_1112.htm")
    doc = Hpricot fetch("http://splus.cumulus.vub.ac.be:1184/2evenjr/opleidingsonderdelen_evenjr.html")

    elems = doc/ :option

    elems.shift
    count = 0
    errormsg += "no data fetched<br />" if elems.empty?
    elems.each do |op|
      page = Hpricot fetch(locus_url + op.inner_html.strip.gsub(/ /, "+"))
      tables = page/ :table
      tables.reject! do |t|
        t.attributes["class"] !~ /spreadsheet|label-border-args/
      end

      until tables.empty? do
        tn = tables.shift
        name = tn.at("span[@class=label-1-0-0]").inner_html
        tc = []
        tc = tables.shift if tables.first.attributes["class"] =~ /spreadsheet/
          rows = tc.search("tr[@class='']")
        lectures = rows.map do |r|
          cols = r/ :td
          cols.map do |c|
            c.inner_html
          end
        end
        @courses[name] = lectures
      end
    end

    errormsg += "no courses found<br />" if @courses.empty?

    lecture_inserts = []
    ActiveRecord::Base.transaction do
      Hash[@courses.sort].each do |name, lectures|
        course = Course.find_by_id_or_name(name) || Course.create(:name => name)
        lectures.each do |l|
          profname = I18n.transliterate l[6]
          prof = Prof.find_by_id_or_name(profname) || Prof.create(:name => profname)
          l = l.map{|v| v.gsub(/&nbsp;/," ").gsub(/^\s*|\s*$/,"")}
          if l[1] && l[2] && l[3] && (l[1] != "") && (l[2] != "") && (l[3] != "") && (l[2].to_i != 0) && (l[3].to_i != 0)
            lecture_inserts << "(\"#{l[0].gsub(/"/,"'")}\", "+
                             "#{(days[l[1].gsub(/[^a-z]/,"")]||0)}, "+
                             "#{l[2].gsub(/"/,"'").gsub(/&nbsp;|:/,"").to_i}, "+
                             "#{l[3].gsub(/"/,"'").gsub(/&nbsp;|:/,"").to_i}, "+
                             "\"#{l[5].gsub(/"/,"'").gsub(/&nbsp;/,"")}\", "+
                             "\"#{l[7].gsub(/"/,"'")}\", "+
                             "#{prof.id}, "+
                             "#{course.id})"
          end
        end
      end
    end

    until lecture_inserts.empty? do
      sql = "insert into `lectures` (`name`, `day`, `starts`, `ends`, `weeks`, `room`, `prof_id`, `course_id`) values #{lecture_inserts.shift(1000).join(", ")}"
      Lecture.connection.execute sql
    end

    respond_to do |format|
      format.html { render :layout => false, :text => errormsg }
    end
  rescue Exception => e
    errormsg += e.message + "<br />"
    respond_to do |format|
      format.html { render :layout => false, :text => errormsg }
    end
  end
end

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<% form_for @course, :url => save_custom_course_path(@student.name, @course.id) do |f| %>
  <%= hidden_field_tag 'course[student_id]', @student.id %>
  <p>
    Name: <%= text_field :course, :name %>
  </p>

  <p>
    <table id="lectures" name="lectures">
      <tr>
        <th>Name</th>
        <th>Room</th>
        <th>Weeks</th>
        <th>Day</th>
        <th>Starts</th>
        <th>Ends</th>
      </tr>
      <% nr = 0 %>
      <% @course.lectures.each do |lecture| %>
        <tr id="lectures_<%= nr %>">
          <%= hidden_field_tag "lectures[#{nr}][id]", lecture.id %>
          <td><%= text_field_tag "lectures[#{nr}][name]", lecture.name %></td>
          <td><%= text_field_tag "lectures[#{nr}][room]", lecture.room %></td>
          <td><%= text_field_tag "lectures[#{nr}][weeks]", lecture.weeks %></td>
          <td><%= text_field_tag "lectures[#{nr}][day]", lecture.day %></td>
          <td><%= text_field_tag "lectures[#{nr}][starts]", lecture.starts %></td>
          <td><%= text_field_tag "lectures[#{nr}][ends]", lecture.ends %></td>
          <td><%= link_to "Remove", remove_custom_lecture_path(nr, lecture.id), :remote => true %></td>
        </tr>
        <% nr += 1 %>
      <% end %>
    </table>
    <div id="add_link"><%= link_to "Add", add_custom_lecture_path(nr), :remote => true %></div>
  </p>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Back', show_path(@student.name) %>

app/views/courses/list.html.erb
<h1>Course#list</h1>
<p>Find me in app/views/course/list.html.erb</p>

app/views/courses/show.html.erb
<h1><%= @course.name %></h1>

<table>
  <tr>
    <th>Lectures</th>
    <th>day</th>
    <th>start</th>
    <th>end</th>
    <th>room</th>
    <th>weeks</th>
    <th>given by</th>
  </tr>
  <% @course.lectures.each do |l| %>
    <tr>
      <td><%= l.name %></td>
      <td><%= l.day %></td>
      <td><%= l.starts %></td>
      <td><%= l.ends %></td>
      <td><%= l.room %></td>
      <td><%= l.weeks %></td>
      <td><%= l.prof.name %></td>
    </tr>
  <% end %>
</table>